export const posts = [
    { 
        id: 1, 
        slug: 'ushuaia-the-city-of-the-end-of-the-world', 
        title: 'Ushuaia, the city of the end of the world',
        date: '1976-04-19T12:59-0500',
        image: 'ushuaia.jpg',
        caption: 'This city is known for the Fitz Roy mount and the numerous trekking paths around the city.',
        subtitle: 'In the southest point of Argentina and the American continent we find the most nearest city to the Antartica.',
        content: 'Nulla elementum velit sapien, vel aliquam tellus venenatis eu. Aliquam at dolor accumsan nisi sodales sodales. Suspendisse augue augue, dictum eget dolor vel, elementum gravida mauris. Morbi non nisi mi. Morbi pretium, lacus a semper fringilla, augue orci euismod velit, facilisis porta orci purus eget ex. Morbi in elit pulvinar, aliquam purus eget, dignissim quam. Vivamus consectetur, justo at molestie commodo, arcu turpis pretium nisi, et tristique dui leo quis dui. Proin hendrerit eros non nulla vehicula scelerisque.', 
    }, 
    { 
        id: 2, 
        slug: 'el-calafate-the-land-of-the-giant-glaciers', 
        title: 'El Calafate, the land of the giant glaciers',
        date: '1976-04-19T12:59-0500',
        image: 'calafate.jpg',
        caption: 'This city is known for the Fitz Roy mount and the numerous trekking paths around the city.',
        subtitle: 'Famous city known by the Perito Moreno glacier, one of the bigest in the world.',
        content: 'Nulla elementum velit sapien, vel aliquam tellus venenatis eu. Aliquam at dolor accumsan nisi sodales sodales. Suspendisse augue augue, dictum eget dolor vel, elementum gravida mauris. Morbi non nisi mi. Morbi pretium, lacus a semper fringilla, augue orci euismod velit, facilisis porta orci purus eget ex. Morbi in elit pulvinar, aliquam purus eget, dignissim quam. Vivamus consectetur, justo at molestie commodo, arcu turpis pretium nisi, et tristique dui leo quis dui. Proin hendrerit eros non nulla vehicula scelerisque.', 
    },  
    { 
        id: 3, 
        slug: 'el-chalten-trekking-national-captial', 
        title: 'El Chalten, trekking national captial',
        date: '1976-04-19T12:59-0500',
        image: 'el-chalten.jpg',
        caption: 'This city is known for the Fitz Roy mount and the numerous trekking paths around the city.',
        subtitle: 'This city is known for the Fitz Roy mount and the numerous trekking paths around the city.',
        content: 'Nulla elementum velit sapien, vel aliquam tellus venenatis eu. Aliquam at dolor accumsan nisi sodales sodales. Suspendisse augue augue, dictum eget dolor vel, elementum gravida mauris. Morbi non nisi mi. Morbi pretium, lacus a semper fringilla, augue orci euismod velit, facilisis porta orci purus eget ex. Morbi in elit pulvinar, aliquam purus eget, dignissim quam. Vivamus consectetur, justo at molestie commodo, arcu turpis pretium nisi, et tristique dui leo quis dui. Proin hendrerit eros non nulla vehicula scelerisque.', 
    }, 
    { 
        id: 4, 
        slug: 'iguazu-falls-natural-wonder', 
        title: 'Iguazu falls natural wonder',
        date: '1976-04-19T12:59-0500',
        image: 'iguazu.jpg',
        caption: 'Voted as one of the 7 Natural Wonders of the World, Iguazu Falls is undoubtedly the most visited place in Misiones and one of the most imposing natural attractions in Argentina and the World.',
        subtitle: 'Voted as one of the 7 Natural Wonders of the World, Iguazu Falls is undoubtedly the most visited place in Misiones and one of the most imposing natural attractions in Argentina and the World.',
        content: 'Nulla elementum velit sapien, vel aliquam tellus venenatis eu. Aliquam at dolor accumsan nisi sodales sodales. Suspendisse augue augue, dictum eget dolor vel, elementum gravida mauris. Morbi non nisi mi. Morbi pretium, lacus a semper fringilla, augue orci euismod velit, facilisis porta orci purus eget ex. Morbi in elit pulvinar, aliquam purus eget, dignissim quam. Vivamus consectetur, justo at molestie commodo, arcu turpis pretium nisi, et tristique dui leo quis dui. Proin hendrerit eros non nulla vehicula scelerisque.', 
    }, 
    { 
        id: 5, 
        slug: 'peninsula-valdes-more-than-whales-watching', 
        title: 'Peninsula Valdes, more than whales watching',
        date: '1976-04-19T12:59-0500',
        image: 'peninsula-valdes.jpg',
        caption: 'Peninsula Valdés is the most important geographical feature of the Argentine coast. It is located in the northern stretch of the coast of Patagonia, in the province of Chubut.',
        subtitle: 'Peninsula Valdés is the most important geographical feature of the Argentine coast. It is located in the northern stretch of the coast of Patagonia, in the province of Chubut.',
        content: 'Nulla elementum velit sapien, vel aliquam tellus venenatis eu. Aliquam at dolor accumsan nisi sodales sodales. Suspendisse augue augue, dictum eget dolor vel, elementum gravida mauris. Morbi non nisi mi. Morbi pretium, lacus a semper fringilla, augue orci euismod velit, facilisis porta orci purus eget ex. Morbi in elit pulvinar, aliquam purus eget, dignissim quam. Vivamus consectetur, justo at molestie commodo, arcu turpis pretium nisi, et tristique dui leo quis dui. Proin hendrerit eros non nulla vehicula scelerisque.', 
    },  
    { 
        id: 6, 
        slug: 'the-lost-city-at-talampaya-national-park', 
        title: 'The lost city at Talampaya national park',
        date: '1976-04-19T12:59-0500',
        image: 'talampaya.jpg',
        caption: 'Visiting the Lost City and the Rainbow Canyon is one of the favorite tours inside Talampaya National Park.',
        subtitle: 'Visiting the Lost City and the Rainbow Canyon is one of the favorite tours inside Talampaya National Park.',
        content: 'Nulla elementum velit sapien, vel aliquam tellus venenatis eu. Aliquam at dolor accumsan nisi sodales sodales. Suspendisse augue augue, dictum eget dolor vel, elementum gravida mauris. Morbi non nisi mi. Morbi pretium, lacus a semper fringilla, augue orci euismod velit, facilisis porta orci purus eget ex. Morbi in elit pulvinar, aliquam purus eget, dignissim quam. Vivamus consectetur, justo at molestie commodo, arcu turpis pretium nisi, et tristique dui leo quis dui. Proin hendrerit eros non nulla vehicula scelerisque.', 
    }, 
  ]

export const comments = [
    {
        id: 1,
        author: 'Pablo Pietra',
        date: '1976-04-19T12:59-0500',
        message: 'Vivamus nisi sapien, efficitur a sodales in, blandit venenatis erat. Vestibulum ac vulputate leo. Cras nec feugiat lectus, in tincidunt nibh. Nullam sed orci nibh. Nulla laoreet vitae nibh vitae tempor. Vivamus pharetra arcu scelerisque vestibulum molestie. Proin at ligula sed leo placerat dapibus in vel ligula.',
        post: 'ushuaia-the-city-of-the-end-of-the-world',
    },
    {
        id: 2,
        author: 'Pablo Pietra',
        date: '1976-04-19T12:59-0500',
        message: 'Vivamus nisi sapien, efficitur a sodales in, blandit venenatis erat. Vestibulum ac vulputate leo. Cras nec feugiat lectus, in tincidunt nibh. Nullam sed orci nibh. Nulla laoreet vitae nibh vitae tempor. Vivamus pharetra arcu scelerisque vestibulum molestie. Proin at ligula sed leo placerat dapibus in vel ligula.',
        post: 'ushuaia-the-city-of-the-end-of-the-world',
    }
]